apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: samikshav/backend:latest
          ports:
            - containerPort: 8090
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_USER
              value: "admin"
            - name: DB_PASSWORD
              value: "admin@123"
            - name: DB_NAME
              value: "employeedb"

